/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestBtn {
    }
    interface TestContainer {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestBtnElement extends Components.TestBtn, HTMLStencilElement {
    }
    var HTMLTestBtnElement: {
        prototype: HTMLTestBtnElement;
        new (): HTMLTestBtnElement;
    };
    interface HTMLTestContainerElement extends Components.TestContainer, HTMLStencilElement {
    }
    var HTMLTestContainerElement: {
        prototype: HTMLTestContainerElement;
        new (): HTMLTestContainerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "test-btn": HTMLTestBtnElement;
        "test-container": HTMLTestContainerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestBtn {
    }
    interface TestContainer {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "test-btn": TestBtn;
        "test-container": TestContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-btn": LocalJSX.TestBtn & JSXBase.HTMLAttributes<HTMLTestBtnElement>;
            "test-container": LocalJSX.TestContainer & JSXBase.HTMLAttributes<HTMLTestContainerElement>;
        }
    }
}
